Numpy 的使用

## 1 创建数组


In [27]:
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import math


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)
print(arr.shape)
# 多维数组
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr1.shape)
# 利用属性强制的转换形状
# 注：从(3,4)改为(4,3)并不是对数组进行转置，
# 而只是改变每个轴的大小，数组元素在内存中的位置并没有改变
arr1.shape = 3, 2
print(arr1)
# 利用广播创建数组
a = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
print(a)
print(a.shape)
print(a.dtype)
b = np.array([[1, 3, 4, 5], [1, 3, 4, 5]], dtype=float)
print(b)
print(b.dtype)


[1 2 3 4 5 6]
(6,)
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
(6, 6)
int32
[[1. 3. 4. 5.]
 [1. 3. 4. 5.]]
float64


In [29]:
# 创建等差数组 start , end , step length
c = np.linspace(0, 20, 5, endpoint=True)
print('b = ', c)
# 创建等比数组 start , end 
# 下面创建起始值为2^0，终止值为2^10(包括)，有10个数的等比数列
d = np.logspace(0, 10, 11, endpoint=True, base=2)
print(d)


## 常用的存取

In [30]:
arr3 = np.arange(0, 22, 2)
print(arr3)


In [31]:
# 获取 某个 
print(arr3[5])
# 获取 3-6个 
print(arr3[3:6])
# 多维数组 
multi = np.arange(0, 60, 10).reshape((-1, 1)) + np.arange(6)
print(multi)

10
[ 6  8 10]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [32]:
# 获取某一个 
print(multi[0, 1])
print("=================")
# 从第2行开始
print(multi[2:])
print("=================")
# 倒数3行
print(multi[:3])
print("=================")
# # # 二维数组的切片
# multi sub[0,2]
print(multi[[0, 1, 2], [2, 3, 4]])

print(multi[4, [2, 3, 4]])
print(multi[4:, [2, 3, 4]])


1
[[20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]]
[ 2 13 24]
[42 43 44]
[[42 43 44]
 [52 53 54]]


In [35]:
#FangSong/黑体 FangSong/KaiTi
mpl.rcParams['font.sans-serif'] = [u'SimHei']  
mpl.rcParams['axes.unicode_minus'] = False
mu = 0
sigma = 1
x = np.linspace(mu - 3 * sigma, mu + 3 * sigma, 51)
y = np.exp(-(x - mu) ** 2 / (2 * sigma ** 2)) / (math.sqrt(2 * math.pi) * sigma)
print(x.shape)
plt.figure(facecolor='rc')
plt.plot(x, y, 'ro-', linewidth=2)
plt.plot(x, y, 'r-', x, y, 'go', linewidth=2, markersize=8)
plt.xlabel('X', fontsize=15)
plt.ylabel('Y', fontsize=15)
plt.title(u'高斯分布函数', fontsize=18)    #
plt.grid(True)
plt.show()


(51,)


ValueError: Invalid RGBA argument: 'rc'