In [28]:
import tensorflow as tf


In [29]:
x = tf.Variable([1, 2])
a = tf.constant([3, 3])
# 增加一个减法 
sub = tf.subtract(x, a)
add = tf.add(x, a)
hello = tf.constant("hello world")
    
with tf.Session() as session:
    session.run(x.initializer)
    print(session.run(sub))
    print(session.run(add))
    print(session.run(hello))


[-2 -1]
[4 5]
b'hello world'


In [30]:
# 创建变量 tf.random_normal 返回形状为（1，4）的张量 4个元素满足 标准差0.35 均值100 的正态分布
w = tf.Variable(initial_value=tf.random_normal(shape=(1, 4), mean=100, stddev=0.35), name='w')
b = tf.Variable(tf.zeros([4]),name = 'b')

[w, b]

[<tf.Variable 'w_2:0' shape=(1, 4) dtype=float32_ref>,
 <tf.Variable 'b_2:0' shape=(4,) dtype=float32_ref>]

In [31]:
session = tf.Session()
session.run(tf.global_variables_initializer())
session.run([w, b])


[array([[100.17237 , 100.00002 , 100.351875, 100.46447 ]], dtype=float32),
 array([0., 0., 0., 0.], dtype=float32)]

In [32]:
session.run(tf.assign_add(b,[1, 1, 1, 1]))


array([1., 1., 1., 1.], dtype=float32)

In [33]:
session.run(b)


array([1., 1., 1., 1.], dtype=float32)

# Saver 使用

    # 创建Saver 
    v1 = tf.Variable(...,name='v1')
    v2 = tf.Variable(...,name='v2')
    # 指定需要保存和恢复的变量
    # 支持存入的方式 1.key:value 2.列表 3.循环
    saver = tf.train.Saver({'v1':v1, 'v2':v2})
    saver = tf.train.Saver([v1, v2])
    saver = tf.train.Saver({v.op.name:v for v in[v1, v2]})

    # 保存变量的方法 filename ===> 'my-model-0' global step 指明当前的步数
    tf.train.saver.save(session,'my-model', global_step=0)

In [34]:
# 创建Saver 
saver = tf.train.Saver({'w': w, 'b': b})
saver.save(session, './summary/test_ckpt', global_step=0)


'./summary/test_ckpt-0'

In [35]:
session.run(tf.assign_add(b, [1, 1, 1, 1]))
session.run(b)


array([2., 2., 2., 2.], dtype=float32)

In [36]:
# 从文件中恢复变量 b 的值
saver.restore(session, './summary/test_ckpt-0')
session.run(b)


INFO:tensorflow:Restoring parameters from ./summary/test_ckpt-0


array([1., 1., 1., 1.], dtype=float32)

In [14]:
# 从文件中恢复数据流图结构
# tf.train.import_meta_graph
